### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by handicraftsman** [Kosti1/WebSite#3]
Remade headerBar. Now updating all already-remade pages to add support of this function

**Comment by handicraftsman** [comment]
You can find menu items in js/header.js

**Comment by handicraftsman** [comment]
Moving 404.html to /

**Comment by handicraftsman** [comment]
P. S. If you'll add some things to this project - try to save them as variables/code in js/header.js.

**Comment by handicraftsman** [comment]
Should i merge to master?

**Comment by handicraftsman** [comment]
Hotfixed. Now it must work

**Comment by handicraftsman** [comment]
P. S. There's already some dropdowns for you in js/header.js

**Comment by Kosti1** [comment]
hi bye

**Comment by AcridBrimistic** [comment]
Project dead?

**Comment by handicraftsman** [comment]
As you see =\

**Comment by Kosti1** [comment]
Ill revive the project!
